blank_issues_enabled: false
contact_links:
  - name: Telegram Channel
    url: https://t.me/AikoCute_Support
    about: Telegram Channel

  - name: Telegram Group
    url: https://t.me/aikocutehotme
    about: Telegram Group
